apiVersion: v1
kind: Pod
metadata:
  name: microcolor-pod
spec:
  containers:
    - name: micro-color
      image: microsudo/micro_color:v1
      ports:
        - containerPort: 8080
      env:
        - name: APP_COLOR
          valueFrom:
           configMapKeyRef:
             name: app-config
             key: APP_COLOR 