apiVersion: v1
kind: Pod
metadata:
  name: microcolor-pod
  labels:
    app: micro-color 
spec:
  containers:
    - name: micro-color
      image: microsudo/micro_color:v1
      ports:
        - containerPort: 8080
  volumes:
    - name: app-config-volume
      configMap:
        name: app-config 